---
certmanage_stable_os:
  - CentOS 7
  - CentOS 8
  - Debian 9
  - Debian 10
  - Debian 11
  - Fedora 30
  - Fedora 31
  - Fedora 32
  - Fedora 33
  - Fedora 34
  - Fedora 35
  - Fedora 36
  # - openSUSE Leap 15
  # - openSUSE Leap 42
  - Ubuntu 16
  - Ubuntu 18
  - Ubuntu 20
  - Ubuntu 22

certmanage_certificates:
  - name: example_certificate
    cert: |
      -----BEGIN CERTIFICATE-----
      [ ... ]
      -----END CERTIFICATE-----
