---
galaxy_info:
  role_name: common
  author: thorian93
  description: Common System Management
  license: "license (MIT)"

  min_ansible_version: "2.9"

  galaxy_tags:
    - linux
    - server
    - common

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - Stretch
        - Buster
        - Bullseye
    - name: Fedora
      versions:
        - 32
        - 33
        - 34
        - 35
        - 36
    - name: SLES
      versions:
        - 11
        - 12
    - name: Ubuntu
      versions:
        - Xenial
        - Bionic
        - Focal
