---
upgrade_stable_os:
  - CentOS-8
  - Debian-10
  - Debian-11
  - Debian-12
  - Debian-13
  - Fedora-42
  - openSUSE Leap-15
  - openSUSE Leap-42
  - SLES-11
  - SLES-12
  - Rocky-9
  - Rocky-10
  - Ubuntu-18
  - Ubuntu-20
  - Ubuntu-22
  - Ubuntu-24

# Basic
upgrade_packages_on_hold: []
upgrade_unattended_reboot: true
upgrade_force_reboot: false
upgrade_needrestart_disable_interaction: true
upgrade_restart_services: true
upgrade_restart_services_blacklist:
  - auditd
  - dbus
  - systemd-manager

# Reporting
upgrade_reporting_enable: false
upgrade_reporting_path: "."
upgrade_reporting_cleanup: true

## Telegram
upgrade_reporting_telegram_enable: false
upgrade_telegram_token: []
upgrade_telegram_chatid: []

## Mail
upgrade_reporting_mail_enable: false
upgrade_reporting_mail_subject: "Ansible Update Role Reporting"
upgrade_reporting_mail_to: ""
upgrade_reporting_mail_from: ""
upgrade_reporting_mail_host: ""
upgrade_reporting_mail_port: ""
upgrade_reporting_mail_user:
upgrade_reporting_mail_password:
upgrade_reporting_mail_run_once: true
