---
galaxy_info:
  role_name: journald
  author: thorian93
  description: Journald logging daemon
  license: "license (MIT)"

  min_ansible_version: "2.9"

  galaxy_tags:
    - linux
    - server

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8
    - name: Debian
      versions:
        - Jessie
        - Stretch
        - Buster
        - Bullseye
    - name: Fedora
      versions:
        - 30
        - 31
        - 32
        - 33
        - 34
        - 35
    - name: SLES
      versions:
        - 11
        - 12
    - name: opensuse
      versions:
        - 15.2
        - 42.2
    - name: Ubuntu
      versions:
        - Trusty
        - Xenial
        - Bionic
        - Focal
