---
logrotate_stable_os:
  - CentOS 7
  - CentOS 8
  - Debian 9
  - Debian 10
  - Debian 11
  - Debian 12
  - Fedora 30
  - Fedora 31
  - Fedora 32
  - Fedora 33
  - Fedora 34
  - Fedora 35
  - SLES 11
  - SLES 12
  - openSUSE Leap 15
  - openSUSE Leap 42
  - Ubuntu 16
  - Ubuntu 18
  - Ubuntu 20
  - Ubuntu 22

logrotate_manage_mysql: false
logrotate_manage_webserver: false

logrotate_interval: "weekly"
logrotate_keep: "7"
logrotate_create: "create"
logrotate_compress: "compress"
logrotate_misc_options: []

logrotate_custom_configs: []
# - name: 'example'
#   files: '/var/log/example.log'
#   interval: daily
#   rotate: '7'
#   options:
#     - missingok
#     - compress
#     - delaycompress
#     - dateext
#     - su root root
